# Generated by Django 6.1.1 on 2026-09-19 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debt_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_lender", models.CharField(max_length=30)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                (
                    "annual_interest_rate",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "monthly_repayment",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                ("montthly_payment_date", models.DateField()),
                ("editor_owner", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="DebtHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField(verbose_name="記録年月")),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="当月返済額"
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="当月発生利息"
                    ),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="返済後残高"
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.debt_information",
                        verbose_name="対象の借金",
                    ),
                ),
            ],
        ),
    ]
