# Generated by Django 6.1.1 on 2026-09-20 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debt_information",
            name="montthly_payment_date",
        ),
        migrations.AddField(
            model_name="debt_information",
            name="monthly_payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="毎月の返済日"),
        ),
        migrations.AlterField(
            model_name="debt_information",
            name="annual_interest_rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=5, verbose_name="年間利率"
            ),
        ),
        migrations.AlterField(
            model_name="debt_information",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="現在の残高"
            ),
        ),
        migrations.AlterField(
            model_name="debt_information",
            name="editor_owner",
            field=models.CharField(max_length=30, verbose_name="更新者"),
        ),
        migrations.AlterField(
            model_name="debt_information",
            name="monthly_repayment",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="月次の返済額"
            ),
        ),
        migrations.AlterField(
            model_name="debt_information",
            name="name_lender",
            field=models.CharField(max_length=30, verbose_name="借入先名"),
        ),
        migrations.CreateModel(
            name="RepaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repayment_amount", models.IntegerField(verbose_name="返済額")),
                (
                    "repayment_date",
                    models.DateField(auto_now_add=True, verbose_name="返済日"),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.debt_information",
                        verbose_name="借入先",
                    ),
                ),
            ],
        ),
    ]
