# Generated by Django 6.1.1 on 2026-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_debt_information_montthly_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt_information",
            name="annual_interest_rate",
            field=models.DecimalField(
                decimal_places=3, max_digits=6, verbose_name="年間利率"
            ),
        ),
        migrations.AlterField(
            model_name="debt_information",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=0, max_digits=20, verbose_name="現在の残高"
            ),
        ),
    ]
